--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iZeaoGamer/QuestPlugin
build-by-default: true
branches:
- patch-1
projects:
  QuestPlugin:
    path: ""
     libs:
    - src: thebigsmilexd/customui/customui
      version: ^3.0.0
    - src: poggit/libasynql/libasynql
      version: ^3.2.0
...
